# Generated by Django 5.1.6 on 2025-03-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myinformation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='myinformation',
            name='last_name',
            field=models.CharField(default='Dhakal', max_length=255),
            preserve_default=False,
        ),
    ]
