# Generated by Django 5.1.6 on 2025-03-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_rename_name_myinformation_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myinformation',
            name='photo',
            field=models.ImageField(default='', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
