# Generated by Django 5.1.7 on 2025-04-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_myinformation_address_myinformation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinformation',
            name='map_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
